Repository openshift-kni/lifecycle-agent, pull requests merged in 2023-12, with the labels that each got.

#136 Auto create initial IBU
  main/main.go
Labels: lgtm, approved

#137 Update .gitattributes
  .gitattributes
Labels: lgtm, approved

#138 Change IBU to cluster scoped
  HACKING.md
  api/v1alpha1/types.go
  bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
  bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
  config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
  config/samples/lca_v1alpha1_imagebasedupgrade.yaml
  controllers/ibu_controller_test.go
  main/main.go
Labels: lgtm, approved

#139 Disable http2 on the rbac proxy
  bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved

#125 Pivot to new stateroot
  controllers/ibu_controller.go
  controllers/idle_handlers.go
  controllers/prep_handlers.go
  controllers/upgrade_handlers.go
  ibu-imager/ostreeclient/mock_rpmostreeclient.go
  ibu-imager/ostreeclient/rpmostreeclient.go
Labels: lgtm, approved

#147 Update tar usage when saving /etc files
  ibu-imager/seedcreator/seedcreator.go
Labels: lgtm, approved, ok-to-test

#146 Catch file not found error properly when restoring/creating IBU
  main/main.go
Labels: lgtm, approved

#145 CNF-10554: seedgen: Add system validation check
  bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/seedgen_controller.go
Labels: lgtm, approved

#148 MGMT-16344: waiting for ovn to exit after node deletion and before stopping all containers
  ibu-imager/ops/ops.go
  ibu-imager/seedcreator/seedcreator.go
Labels: lgtm, approved

#149 OCPEDGE-664: Pregenerate kubelet certs to skip post-pivot CSR approvals
  ibu-imager/clusterinfo/clusterinfo.go
  ibu-imager/postpivot/postpivot.go
  internal/clusterconfig/clusterconfig_test.go
  internal/recert/recert.go
Labels: lgtm, approved

#129 Convert prep scripts to golang
  controllers/ibu_controller.go
  controllers/prep_handlers.go
  ibu-imager/ops/mock_ops.go
  ibu-imager/ops/ops.go
  ibu-imager/ostreeclient/mock_rpmostreeclient.go
  ibu-imager/ostreeclient/rpmostreeclient.go
  internal/bindata/prepCleanup.sh
  internal/bindata/prepSetupStateroot.sh
  internal/common/utils.go
  internal/generated/zz_generated.bindata.go
  internal/ostreeclient/mock_ostreeclient.go
  internal/ostreeclient/ostreeclient.go
  internal/prep/prep.go
  internal/prep/prep_test.go
  main/main.go
Labels: lgtm, approved

#150 Refactor recert run usage
  ibu-imager/ops/mock_ops.go
  ibu-imager/ops/ops.go
  ibu-imager/postpivot/postpivot.go
Labels: lgtm, approved

#154 Fix prep failing when version had multiple dashes
  controllers/prep_handlers.go
  internal/prep/prep.go
  internal/prep/prep_test.go
Labels: lgtm, approved

#156 Add flag for seedcreator that allows to skip cleanup part
  ibu-imager/cmd/create.go
  ibu-imager/cmd/root.go
Labels: lgtm, approved

#144 health check
  bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/upgrade_handlers.go
  internal/common/utils.go
  internal/healthcheck/healthcheck.go
Labels: lgtm, approved

#157 Update health checks
  bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/healthcheck/healthcheck.go
Labels: lgtm, approved

#155 MGMT-16227: cleanup etcd keys with seed hostname in them and small fixes for IBI process
  ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
  ibu-imager/ops/ops.go
  ibu-imager/postpivot/postpivot.go
  internal/recert/recert.go
Labels: lgtm, approved

#140 Add ExecuteWithLiveLogger and stop logging commands output by default
  ibu-imager/ops/execute.go
  main/main.go
Labels: lgtm, approved

#153 Upgrade post pivot with extra manifest apply and OADP restore
  controllers/upgrade_handlers.go
  controllers/utils/conditions.go
  internal/backuprestore/backup.go
  internal/backuprestore/backup_test.go
  internal/backuprestore/common.go
  internal/backuprestore/restore.go
  internal/backuprestore/restore_test.go
  internal/common/utils.go
  internal/extramanifest/extramanifest.go
  internal/extramanifest/extramanifest_test.go
Labels: lgtm, approved

#159 Fix reconciliation for upgrade
  controllers/upgrade_handlers.go
Labels: lgtm, approved

#161 Change registry for precache job in case snoa and seed registry differs
  controllers/prep_handlers.go
  ibu-imager/clusterinfo/clusterinfo.go
  ibu-imager/postpivot/postpivot.go
  utils/utils.go
  utils/utils_test.go
Labels: lgtm, approved

#143 Add handleFinalize and perform backup cleanups
  controllers/idle_handlers.go
  controllers/idle_handlers_test.go
  internal/backuprestore/backup.go
  internal/backuprestore/common.go
  internal/ostreeclient/mock_ostreeclient.go
  internal/ostreeclient/ostreeclient.go
Labels: lgtm, approved

#163 Fix kernel arguments quoting
  internal/prep/prep.go
  internal/prep/prep_test.go
Labels: lgtm, approved

#164 Remove bindata from HACKING.md
  HACKING.md
Labels: lgtm, approved

#166 Don't change registry if seed or cluster registry are empty
  utils/utils.go
Labels: lgtm, approved

#165 Create doc for using backup and restore
  docs/backuprestore-with-oadp.md
Labels: lgtm, approved

#162 Refactor: Move network config to clusterconfig
  controllers/ibu_controller.go
  controllers/prep_handlers.go
  controllers/upgrade_handlers.go
  controllers/utils/constants.go
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/clusterconfig/lvmconfig.go
  internal/clusterconfig/lvmconfig_test.go
  internal/clusterconfig/networkconfig.go
  internal/clusterconfig/networkconfig_test.go
  internal/common/consts.go
  internal/common/utils.go
  internal/precache/helper.go
  internal/precache/helper_test.go
  main/main.go
  main/precache-workload/main.go
Labels: lgtm, approved

#160 CNF-10412: Remove progress file from the prep-handler
  controllers/ibu_controller.go
  controllers/idle_handlers.go
  controllers/prep_handlers.go
  controllers/utils/conditions.go
  controllers/utils/constants.go
  go.mod
  internal/precache/constants.go
  internal/precache/precache.go
  main/main.go
Labels: lgtm, approved

#168 Fix condition for mounting config ISO
  ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
Labels: lgtm, approved, needs-ok-to-test

#170 Merge SCC access to the single manager role and makefile adjustment for bundle test
  HACKING.md
  Makefile
  bundle/manifests/lifecycle-agent-manager-privileged-scc-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/lifecycle-agent-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/lifecycle-agent-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  main/main.go
Labels: lgtm, approved

#172 Some changes to backup&restore plugin
  controllers/upgrade_handlers.go
  docs/backuprestore-with-oadp.md
  internal/backuprestore/backup.go
  internal/backuprestore/backup_test.go
  internal/backuprestore/common.go
  internal/backuprestore/restore.go
  internal/backuprestore/restore_test.go
  internal/extramanifest/extramanifest.go
  utils/utils.go
Labels: lgtm, approved

#167 upgradeHandler unit tests (handleBackup + handleRestore)
  controllers/ibu_controller.go
  controllers/upgrade_handlers_test.go
  internal/backuprestore/common.go
  internal/backuprestore/mocks/mock_backuprestore.go
Labels: lgtm, approved

#176 seedgen: Fix recert podman pull for disconn registries
  controllers/seedgen_controller.go
Labels: lgtm, approved

#175 Update observedGeneration for conditions related to the current stage
  controllers/ibu_controller.go
Labels: lgtm, approved

#178 Fix condition observedGeneration update
  controllers/ibu_controller.go
Labels: lgtm, approved

#171 Add dev script for summarizing IBU CR
  hack/summarize-ibu.sh
Labels: lgtm, approved

#142 Remove InfoClient and move its functions to utils/client_helper.go
  controllers/ibu_controller.go
  controllers/prep_handlers.go
  controllers/seedgen_controller.go
  ibu-imager/clusterinfo/clusterinfo.go
  ibu-imager/postpivot/postpivot.go
  ibu-imager/seedcreator/seedcreator.go
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/common/consts.go
  internal/prep/prep.go
  main/main.go
  utils/client_helper.go
Labels: lgtm, approved

#180 Complete abort check implementation
  controllers/ibu_controller.go
  controllers/ibu_controller_test.go
Labels: lgtm, approved

#173 Changes required for IBI
  controllers/prep_handlers.go
  ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
  ibu-imager/postpivot/postpivot.go
  ibu-imager/seedcreator/seedcreator.go
  ibu-imager/seedrestoration/seedcleanup.go
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/common/consts.go
  utils/utils.go
Labels: lgtm, approved

#181 Run recert once in seed creator
  ibu-imager/seedcreator/seedcreator.go
Labels: lgtm, approved

#184 Cosmetic: Change prep failure message
  controllers/prep_handlers.go
Labels: lgtm, approved

#182 summarize-ibu prep failure should display `PrepInProgress`
  hack/summarize-ibu.sh
Labels: lgtm, approved

#177 MGMT-16334: [Imager] Add selective cleanup based on successful stages
  ibu-imager/seedrestoration/seedcleanup.go
Labels: lgtm, approved

#185 Update location of seed manifest file in post-pivot
  ibu-imager/postpivot/postpivot.go
  internal/clusterconfig/clusterconfig_test.go
  internal/common/consts.go
Labels: lgtm, approved

#189 Add support for rollback and ostree admin set-default
  HACKING.md
  controllers/ibu_controller.go
  controllers/rollback_handlers.go
  controllers/seedgen_controller.go
  controllers/upgrade_handlers.go
  controllers/utils/conditions.go
  hack/summarize-ibu.sh
  ibu-imager/ostreeclient/mock_rpmostreeclient.go
  ibu-imager/ostreeclient/rpmostreeclient.go
  internal/ostreeclient/mock_ostreeclient.go
  internal/ostreeclient/ostreeclient.go
  main/main.go
Labels: lgtm, approved

#192 CNF-10679: Add spec descriptors for seedImageRef and stage required by scorecard
  api/v1alpha1/types.go
  bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
  config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
Labels: lgtm, approved

#193 Update reboot command to avoid hanging
  controllers/rollback_handlers.go
  controllers/upgrade_handlers.go
Labels: lgtm, approved

#196 precaching: Always pull tagged images
  internal/precache/workload/pullImages.go
Labels: lgtm, approved

#183 Support multi-document YAML in OADP and extra-manifests configmaps
  docs/backuprestore-with-oadp.md
  internal/backuprestore/backup.go
  internal/backuprestore/backup_test.go
  internal/backuprestore/common.go
  internal/backuprestore/restore.go
  internal/extramanifest/extramanifest.go
  internal/extramanifest/extramanifest_test.go
Labels: lgtm, approved

#191 Add printer columns for ibu
  api/v1alpha1/types.go
  bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
  config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
  controllers/utils/conditions.go
Labels: lgtm, approved

#190 health check unit tests
  internal/healthcheck/healthcheck_test.go
Labels: lgtm, approved

#194 Recreate IBU when deleted
  controllers/ibu_controller.go
  main/main.go
  utils/utils.go
Labels: lgtm, approved

#197 Update HACKING.md command for setting PRECACHE_BEST_EFFORT
  HACKING.md
Labels: lgtm, approved

#195 Mirror registry : Adding verification if we should override mirror registry or not
  controllers/prep_handlers.go
  ibu-imager/clusterinfo/clusterinfo.go
  ibu-imager/postpivot/postpivot.go
  utils/client_helper.go
  utils/utils.go
Labels: lgtm, approved
