Repository openshift-kni/lifecycle-agent, pull requests merged in 2025-06, with the labels that each got.

#1083 [release-4.18] Catalog configuration for 4.18
  .konflux/Dockerfile.bundle
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/lifecycle-agent/catalog.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/lifecycle-agent-fbc-4-18-pull-request.yaml
  .tekton/lifecycle-agent-fbc-4-18-push.yaml
  .tekton/lifecycle-agent-operator-bundle-4-18-pull-request.yaml
  .tekton/lifecycle-agent-operator-bundle-4-18-push.yaml
  Makefile
  hack/konflux-update-catalog-template.sh
  hack/konflux-update-task-refs.sh
  hack/konflux-validate-related-images-production.sh
Labels: lgtm

#1088 [release-4.16] Catalog configuration for 4.16
  .konflux/Dockerfile.bundle
  .konflux/Dockerfile.catalog
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/lifecycle-agent/catalog.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/lifecycle-agent-fbc-4-16-pull-request.yaml
  .tekton/lifecycle-agent-fbc-4-16-push.yaml
  .tekton/lifecycle-agent-operator-bundle-4-16-pull-request.yaml
  .tekton/lifecycle-agent-operator-bundle-4-16-push.yaml
  Makefile
  hack/konflux-update-catalog-template.sh
  hack/konflux-update-task-refs.sh
  hack/konflux-validate-related-images-production.sh
Labels: lgtm

#1144 [release-4.19] Align overlay contents with data used in previous releases
  .konflux/overlay/overlay.bash
Labels: lgtm, approved

#1149 [release-4.16] Align overlay contents with data used in previous releases
  .konflux/overlay/overlay.bash
Labels: lgtm, approved

#1171 Fix bundle overlay for recert
  .konflux/overlay/map_images.in.yaml
  .konflux/overlay/pin_images.in.yaml
Labels: lgtm, approved

#1167 Fix bundle overlay for recert
  .konflux/overlay/map_images.in.yaml
  .konflux/overlay/pin_images.in.yaml
Labels: lgtm, approved

#1210 [release-4.19] Prepare for 4.19.1
  .konflux/overlay/overlay.bash
  Makefile
Labels: lgtm

#1057 Add NetworkPolicy support for lifecycle-agent controller
  bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/networkpolicies/controller.go
  main/main.go
Labels: lgtm, approved

#1242 Fix opm image in use
  .konflux/Dockerfile.catalog
  .konflux/container_build_args.conf
Labels: lgtm, approved

#1218 Remove catalog.yaml from git repo
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/lifecycle-agent/.gitkeep
  .konflux/catalog/lifecycle-agent/catalog.yaml
  Makefile
Labels: lgtm, do-not-merge/hold

#1213 Configure catalog to include next z stream build (4.18.1) as a Konflux quay build
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/lifecycle-agent/.gitkeep
  .konflux/catalog/lifecycle-agent/catalog.yaml
  Makefile
Labels: do-not-merge/hold

#1215 Configure catalog to include next z stream build (4.16.4) as a Konflux quay image
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/lifecycle-agent/.gitkeep
  .konflux/catalog/lifecycle-agent/catalog.yaml
  Makefile
Labels: lgtm, do-not-merge/hold

#1249 Configure catalog to include next z stream build (4.15.5) as a Konflux quay image
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/lifecycle-agent/.gitkeep
  .konflux/catalog/lifecycle-agent/catalog.yaml
  Makefile
Labels: lgtm, do-not-merge/hold

#1250 Configure catalog to include next z stream build (4.14.4) as a Konflux quay image
  .konflux/catalog/.gitignore
  .konflux/catalog/README.md
  .konflux/catalog/bundle.builds.in.yaml
  .konflux/catalog/catalog-template.in.yaml
  .konflux/catalog/lifecycle-agent/.gitkeep
  .konflux/catalog/lifecycle-agent/catalog.yaml
  Makefile
Labels: lgtm, do-not-merge/hold
