Repository openshift-kni/lifecycle-agent, pull requests merged in 2025-08, with the labels that each got.

#1894 Upversion golang to 1.24
  .ci-operator.yaml
  .konflux/Dockerfile.catalog
  .konflux/container_build_args.conf
  Dockerfile
  go.mod
  internal/backuprestore/common.go
  internal/extramanifest/extramanifest.go
  internal/healthcheck/healthcheck.go
  lca-cli/cmd/create.go
  lca-cli/cmd/ibuStaterootSetup.go
Labels: lgtm

#1910 Update yamllint configuration and fix warnings
  .ci-operator.yaml
  .github/dependabot.yml
  .golangci.yml
  .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
  .konflux/lock-runtime/rpms.in.yaml
  .konflux/lock-runtime/rpms.lock.yaml
  .konflux/overlay/map_images.in.yaml
  .konflux/overlay/pin_images.in.yaml
  .markdownlint-cli2.yaml
  .tekton/build-pipeline.yaml
  .tekton/fbc-pipeline.yaml
  .tekton/images-mirror-set.yaml
  .tekton/lifecycle-agent-4-20-pull-request.yaml
  .tekton/lifecycle-agent-4-20-push.yaml
  .tekton/lifecycle-agent-fbc-4-20-pull-request.yaml
  .tekton/lifecycle-agent-fbc-4-20-push.yaml
  .tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
  .tekton/lifecycle-agent-operator-bundle-4-20-push.yaml
  .testcoverage.yml
  .yamllint.yaml
  hack/yamllint.sh
Labels: lgtm, approved

#1659 MGMT-21201: Enable dual-stack clusters
  api/seedreconfig/seedreconfig.go
  internal/clusterconfig/clusterconfig.go
  internal/clusterconfig/clusterconfig_test.go
  internal/recert/recert.go
  internal/recert/recert_test.go
  lca-cli/postpivot/postpivot.go
  lca-cli/postpivot/postpivot_test.go
  lca-cli/seedclusterinfo/seedclusterinfo.go
  lca-cli/seedclusterinfo/seedclusterinfo_test.go
  utils/client_helper.go
  utils/client_helper_test.go
Labels: lgtm, approved, ok-to-test

#2179 OCPBUGS-58602: Bump github.com/golang/glog from 1.2.0 to 1.2.4 to resolve CVE-2024-45339
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#1994 OCPBUGS-58604: Bump glog version to 1.2.4 to resolve CVE-2024-45339
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test
